spring.application.name=PlaytheCity
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration


#spring.ai.openai.api-key=sk-MuF8NuH3ANwykXhiPR26og
spring.ai.openai.api-key=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
#spring.ai.openai.base-url=https://api.regolo.ai/v1/chat/completions
#spring.ai.openai.chat.options.model=Llama-3.3-70B-Instruct

foursquare.api.key=Y2E4OIMCCASPMCPLG5YOKM15OKQ0X05HADYXNADAOU4LFU0P